services:
  - type: web
    name: rockola-youtube
    env: node
    plan: free
    preDeployCommand: npm install --include=dev
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production